support Fedora when using bootstrap
Signed-off-by: Greg Farnum <gfarnum@redhat.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -17,6 +17,19 @@ Linux)
             exit 1
         fi
         ;;
+    Fedora)
+        for package in python-pip python-virtualenv libevent-devel libvirt-python community-mysql-devel; do
+	    if [ "$(rpm -q $package)" == "package $package is not installed" ]; then
+		missing="${missing:+$missing }$package"
+	    fi
+	done
+	if [ -n "$missing" ]; then
+            echo "$0: missing required packages, please install them:" 1>&2
+            echo "sudo yum install $missing"
+            exit 1
+	fi
+	;;
+
     *)
         echo "This script does not support your Linux distribution yet. Patches encouraged!"
         exit 1
