Added openSUSE and SLES conditions in bootstrap.
Signed-off-by: Kapil Sharma ksharma@suse.com

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -40,7 +40,18 @@ Linux)
             exit 1
 	fi
 	;;
-
+    "openSUSE project"|"SUSE LINUX")
+        for package in python-pip python-virtualenv libevent-devel libvirt-python libmysqlclient-devel; do
+            if [ "$(rpm -q $package)" == "package $package is not installed" ]; then
+                missing="${missing:+$missing }$package"
+            fi
+        done
+        if [ -n "$missing" ]; then
+            echo "$0: missing required packages, please install them:" 1>&2
+            echo "sudo zypper install $missing"
+            exit 1
+        fi
+        ;;
     *)
         echo "This script does not support your Linux distribution yet. Patches encouraged!"
         exit 1
