Don't assume Ubuntu; also support MacOS X
Signed-off-by: Zack Cerza <zack.cerza@inktank.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,17 +1,47 @@
 #!/bin/sh
 set -e
 
-for package in python-dev python-pip python-virtualenv libevent-dev python-libvirt; do
-    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
-	# add a space after old values
-	missing="${missing:+$missing }$package"
+case "$(uname -s)" in
+Linux)
+    case "$(lsb_release --id --short)" in
+    Ubuntu|Debian)
+        for package in python-dev python-pip python-virtualenv libevent-dev python-libvirt; do
+            if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+                # add a space after old values
+                missing="${missing:+$missing }$package"
+            fi
+        done
+        if [ -n "$missing" ]; then
+            echo "$0: missing required packages, please install them:" 1>&2
+            echo "sudo apt-get install $missing"
+            exit 1
+        fi
+        ;;
+    *)
+        echo "This script does not support your Linux distribution yet. Patches encouraged!"
+        exit 1
+        ;;
+    esac
+    ;;
+Darwin)
+    if ! which brew > /dev/null; then
+        echo "You need Homebrew: http://brew.sh/"
+        exit 1
     fi
-done
-if [ -n "$missing" ]; then
-    echo "$0: missing required packages, please install them:" 1>&2
-    echo "sudo apt-get install $missing"
+    for keg in python libvirt libevent; do
+        if brew list $keg >/dev/null 2>&1; then
+            echo "Found $keg"
+        else
+            brew install keg
+        fi
+    done
+    ;;
+*)
+    echo "This script does not support your OS yet. Patches encouraged!"
     exit 1
-fi
+    ;;
+esac
+exit
 
 if [ -z "$NO_CLOBBER" ] || [ ! -e ./virtualenv ]; then
     # site packages needed because libvirt python bindings are not nicely
