bootstrap: apt/yum install the list of dependencies if missing
Instead of just printing the list and bailing, assume the user has sudo
and actually install them.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -23,9 +23,9 @@ Linux)
             fi
         done
         if [ -n "$missing" ]; then
-            echo "$0: missing required packages, please install them:" 1>&2
-            echo "sudo apt-get install $missing"
-            exit 1
+            echo "$0: missing required packages, installing them:" 1>&2
+            echo "$missing"
+            sudo apt-get -y install $missing
         fi
         ;;
     Fedora)
@@ -35,9 +35,9 @@ Linux)
 	    fi
 	done
 	if [ -n "$missing" ]; then
-            echo "$0: missing required packages, please install them:" 1>&2
-            echo "sudo yum install $missing"
-            exit 1
+            echo "$0: missing required packages, installing them:" 1>&2
+            echo "$missing"
+            sudo yum -y install $missing
 	fi
 	;;
     "openSUSE project"|"SUSE LINUX")
