Revert "Merge pull request #1 from ceph/master"
This reverts commit 853da4b86b4d76b16e1f8655c4513220493a64e1, reversing
changes made to 3daf908ba0e5288031e672dd78966aecffc873cf.

diff --git a/admin/build-doc b/admin/build-doc
--- a/admin/build-doc
+++ b/admin/build-doc
@@ -7,20 +7,19 @@ TOPDIR=`pwd`
 install -d -m0755 build-doc
 
 if command -v dpkg >/dev/null; then
-    packages=`cat ${TOPDIR}/doc_deps.deb.txt`
-    for package in $packages; do
-    if [ "$(dpkg --status -- $package 2>&1 | sed -n 's/^Status: //p')" != "install ok installed" ]; then
-        # add a space after old values
-        missing="${missing:+$missing }$package"
-    fi
+    for package in python-dev python-pip python-virtualenv doxygen ditaa ant libxml2-dev libxslt1-dev cython; do
+	if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+            # add a space after old values
+	    missing="${missing:+$missing }$package"
+	fi
     done
     if [ -n "$missing" ]; then
-        echo "$0: missing required packages, please install them:" 1>&2
-        echo "sudo apt-get install -o APT::Install-Recommends=true $missing" 1>&2
-        exit 1
+	echo "$0: missing required packages, please install them:" 1>&2
+	echo "sudo apt-get install $missing"
+	exit 1
     fi
 elif command -v yum >/dev/null; then
-    for package in python-devel python-pip python-virtualenv doxygen ditaa ant libxml2-devel libxslt-devel Cython graphviz; do
+    for package in python-devel python-pip python-virtualenv doxygen ditaa ant libxml-devel libxslt-devel Cython; do
 	if ! rpm -q $package >/dev/null ; then
 		missing="${missing:+$missing }$package"
 	fi
@@ -57,7 +56,7 @@ cd build-doc
 [ -z "$vdir" ] && vdir="$TOPDIR/build-doc/virtualenv"
 
 if [ ! -e $vdir ]; then
-    virtualenv --system-site-packages $vdir -p python2
+    virtualenv --system-site-packages $vdir
 fi
 $vdir/bin/pip install --quiet -r $TOPDIR/admin/doc-requirements.txt
 
@@ -67,53 +66,21 @@ install -d -m0755 \
 
 # To avoid having to build librbd to build the Python bindings to build the docs,
 # create a dummy librbd.so that allows the module to be imported by sphinx.
-# the module are imported by the "automodule::" directive.
 mkdir -p $vdir/lib
 export LD_LIBRARY_PATH="$vdir/lib"
 export PYTHONPATH=$TOPDIR/src/pybind
+ln -sf librbd.so.1 $vdir/lib/librbd.so
+gcc -shared -o $vdir/lib/librbd.so.1 -xc /dev/null
+CFLAGS="-iquote $TOPDIR/src/include" \
+    CPPFLAGS="-iquote $TOPDIR/src/include" \
+    LDFLAGS="-L$vdir/lib -Wl,--no-as-needed" \
+    $vdir/bin/pip install $TOPDIR/src/pybind
+nm $vdir/lib/python*/*-packages/rbd.so | grep 'U rbd_' | \
+    awk '{ print "void "$2"(void) {}" }' | \
+    gcc -shared -o $vdir/lib/librbd.so.1 -xc -
 
-# FIXME(sileht): I dunno how to pass the include-dirs correctly with pip
-# for build_ext step, it should be:
-# --global-option=build_ext --global-option="--cython-include-dirs $TOPDIR/src/pybind/rados/"
-# but that doesn't work, so copying the file in the rbd module directly, that's ok for docs
-for bind in rados rbd cephfs rgw; do
-    if [ ${bind} != rados ]; then
-        cp -f $TOPDIR/src/pybind/rados/rados.pxd $TOPDIR/src/pybind/${bind}/
-    fi
-    ln -sf lib${bind}.so.1 $vdir/lib/lib${bind}.so
-    gcc -shared -o $vdir/lib/lib${bind}.so.1 -xc /dev/null
-    BUILD_DOC=1 \
-        CFLAGS="-iquote$TOPDIR/src/include" \
-        CPPFLAGS="-iquote$TOPDIR/src/include" \
-        LDFLAGS="-L$vdir/lib -Wl,--no-as-needed" \
-        $vdir/bin/pip install $TOPDIR/src/pybind/${bind}
-    # rgwfile_version(), librgw_create(), rgw_mount()
-    nm $vdir/lib/python*/*-packages/${bind}.so | grep -E "U (lib)?${bind}" | \
-        awk '{ print "void "$2"(void) {}" }' | \
-        gcc -shared -o $vdir/lib/lib${bind}.so.1 -xc -
-    if [ ${bind} != rados ]; then
-        rm -f $TOPDIR/src/pybind/${bind}/rados.pxd
-    fi
-done
-
-if [ -z "$@" ]; then
-    sphinx_targets="html man"
-else
-    sphinx_targets=$@
-fi
-for target in $sphinx_targets; do
-    builder=$target
-    case $target in
-        html)
-            builder=dirhtml
-            ;;
-        man)
-            extra_opt="-t man"
-            ;;
-    esac
-    $vdir/bin/sphinx-build -a -b $builder $extra_opt -d doctrees \
-                           $TOPDIR/doc $TOPDIR/build-doc/output/$target
-done
+$vdir/bin/sphinx-build -a -n -b dirhtml -d doctrees $TOPDIR/doc $TOPDIR/build-doc/output/html
+$vdir/bin/sphinx-build -a -b man -d doctrees $TOPDIR/doc $TOPDIR/build-doc/output/man
 
 #
 # Build and install JavaDocs
diff --git a/src/rbdmap b/src/rbdmap
--- a/src/rbdmap
+++ b/src/rbdmap
@@ -1,6 +1,11 @@
-#!/bin/bash
+#!/bin/sh
 
 do_map() {
+	if [ ! -f "$RBDMAPFILE" ]; then
+		logger -p "daemon.warning" -t init-rbdmap "No $RBDMAPFILE found."
+		exit 0
+	fi
+
 	# Read /etc/rbdtab to create non-existant mapping
 	RET=0
 	while read DEV PARAMS; do
@@ -14,7 +19,7 @@ do_map() {
 			DEV=rbd/$DEV
 			;;
 		esac
-		logger -p "daemon.debug" -t rbdmap "Mapping '${DEV}'"
+		logger -p "daemon.debug" -t init-rbdmap "Mapping '${DEV}'"
 		newrbd=""
 		MAP_RV=""
 		OIFS=$IFS
@@ -32,22 +37,22 @@ do_map() {
 			    newrbd="yes"
 			else
 			    RET=$((${RET}+$?))
-			    logger -p "daemon.warning" -t rbdmap "Failed to map '${DEV}"
+			    logger -p "daemon.warning" -t init-rbdmap "Failed to map '${DEV}"
 			    continue
 			fi
 		fi
-		logger -p "daemon.debug" -t rbdmap "Mapped '${DEV}' to '${MAP_RV}'"
+		logger -p "daemon.debug" -t init-rbdmap "Mapped '${DEV}' to '${MAP_RV}'"
 
 		if [ "$newrbd" ]; then
 			## Mount new rbd
 			MNT_RV=""
 			mount --fake /dev/rbd/$DEV >>/dev/null 2>&1 \
 			&& MNT_RV=$(mount -vn /dev/rbd/$DEV 2>&1)
-			[ -n "${MNT_RV}" ] && logger -p "daemon.debug" -t rbdmap "Mounted '${MAP_RV}' to '${MNT_RV}'"
+			[ -n "${MNT_RV}" ] && logger -p "daemon.debug" -t init-rbdmap "Mounted '${MAP_RV}' to '${MNT_RV}'"
 
 			## post-mapping
 			if [ -x "/etc/ceph/rbd.d/${DEV}" ]; then
-			    logger -p "daemon.debug" -t rbdmap "Running post-map hook '/etc/ceph/rbd.d/${DEV}'"
+			    logger -p "daemon.debug" -t init-rbdmap "Running post-map hook '/etc/ceph/rbd.d/${DEV}'"
 			    /etc/ceph/rbd.d/${DEV} map "/dev/rbd/${DEV}"
 			fi
 		fi
@@ -56,33 +61,7 @@ do_map() {
 
 }
 
-unmount_unmap() {
-	local rbd_dev=$1
-	local mnt=$(findmnt --mtab --source ${rbd_dev} --noheadings \
-							| awk '{print $1'})
-
-	logger -p "daemon.debug" -t rbdmap "Unmapping '${rbd_dev}'"
-	if [ -n "${mnt}" ]; then
-	    logger -p "daemon.debug" -t rbdmap "Unmounting '${mnt}'"
-	    umount "${mnt}" >>/dev/null 2>&1
-	fi
-	if mountpoint -q "${mnt}"; then
-	    ## Un-mounting failed.
-	    logger -p "daemon.warning" -t rbdmap "Failed to unmount '${mnt}'"
-	    return 1
-	fi
-	## Un-mapping.
-	rbd unmap $rbd_dev >>/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    logger -p "daemon.warning" -t rbdmap "Failed to unmap '${mnt}'"
-	    return 1
-	fi
-	logger -p "daemon.debug" -t rbdmap "Unmapped '${rbd_dev}'"
-
-	return 0
-}
-
-do_unmap_all() {
+do_unmap() {
 	RET=0
 	## Unmount and unmap all rbd devices
 	if ls /dev/rbd[0-9]* >/dev/null 2>&1; then
@@ -92,62 +71,36 @@ do_unmap_all() {
 			    LL="${L##/dev/rbd/}"
 			    if [ "$(readlink -f $L)" = "${DEV}" ] \
 			    && [ -x "/etc/ceph/rbd.d/${LL}" ]; then
-			        logger -p "daemon.debug" -t rbdmap "Running pre-unmap hook for '${DEV}': '/etc/ceph/rbd.d/${LL}'"
+			        logger -p "daemon.debug" -t init-rbdmap "Running pre-unmap hook for '${DEV}': '/etc/ceph/rbd.d/${LL}'"
 			        /etc/ceph/rbd.d/${LL} unmap "$L"
 			        break
 			    fi
 			done
 
-			unmount_unmap "$DEV" || RET=$((${RET}+$?))
-
+			logger -p "daemon.debug" -t init-rbdmap "Unmapping '${DEV}'"
+			MNT=$(findmnt --mtab --source ${DEV} --noheadings | awk '{print $1'})
+			if [ -n "${MNT}" ]; then
+			    logger -p "daemon.debug" -t init-rbdmap "Unmounting '${MNT}'"
+			    umount "${MNT}" >>/dev/null 2>&1
+			fi
+			if mountpoint -q "${MNT}"; then
+			    ## Un-mounting failed.
+			    logger -p "daemon.warning" -t init-rbdmap "Failed to unmount '${MNT}'"
+			    RET=$((${RET}+1))
+			    continue
+			fi
+			## Un-mapping.
+			rbd unmap $DEV >>/dev/null 2>&1
+			if [ $? -ne 0 ]; then
+			    logger -p "daemon.warning" -t init-rbdmap "Failed to unmap '${MNT}'"
+			    RET=$((${RET}+$?))
+			    continue
+			fi
+			logger -p "daemon.debug" -t init-rbdmap "Unmapped '${DEV}'"
 		done
 	fi
 	exit ${RET}
 }
-
-do_unmap() {
-	RET=0
-	## skip if nothing is mapped
-	ls /dev/rbd[0-9]* >/dev/null 2>&1 || exit ${RET}
-
-	# Read /etc/rbdtab to create non-existant mapping
-	while read DEV PARAMS; do
-		case "$DEV" in
-		  ""|\#*)
-			continue
-			;;
-		  */*)
-			;;
-		  *)
-			DEV=rbd/$DEV
-			;;
-		esac
-
-		MAP_RV="$(readlink -f /dev/rbd/$DEV)"
-		if [ ! -b $MAP_RV ]; then
-			logger -p "daemon.debug" -t rbdmap "$DEV not mapped, skipping unmap"
-			continue
-		fi
-
-		## pre-unmapping
-		if [ -x "/etc/ceph/rbd.d/${DEV}" ]; then
-			logger -p "daemon.debug" -t rbdmap "Running pre-unmap hook '/etc/ceph/rbd.d/${DEV}'"
-			/etc/ceph/rbd.d/${DEV} unmap "/dev/rbd/${DEV}"
-		fi
-
-		unmount_unmap "$MAP_RV" || RET=$((${RET}+$?))
-
-	done < $RBDMAPFILE
-	exit ${RET}
-}
-
-# default to reasonable value if RBDMAPFILE not set in environment
-RBDMAPFILE="${RBDMAPFILE:-/etc/ceph/rbdmap}"
-
-if [ ! -f "$RBDMAPFILE" ]; then
-	logger -p "daemon.warning" -t rbdmap "No $RBDMAPFILE found."
-	exit 0
-fi
 
 case "$1" in
   map)
@@ -157,11 +110,6 @@ case "$1" in
   unmap)
 	do_unmap
 	;;
-
-  unmap-all)
-	do_unmap_all
-	;;
-
   *)
-	echo "Usage: rbdmap map | unmap | unmap-all"
+	echo "Usage: rbdmap map | unmap"
 esac
