doc: Switch diagram tools from dia to ditaa.
Now you can create diagrams easily with the ".. ditaa::"
directive in the Sphinx documents.

admin/build-doc now checks for debs required for building
the documentation, or just lists commands missing for hosts
not using dpkg.

For more on Ditaa, see http://ditaa.sourceforge.net/

Signed-off-by: Tommi Virtanen <tommi.virtanen@dreamhost.com>

diff --git a/admin/build-doc b/admin/build-doc
--- a/admin/build-doc
+++ b/admin/build-doc
@@ -5,13 +5,35 @@ cd ..
 
 install -d -m0755 build-doc
 
+if command -v dpkg >/dev/null; then
+    for package in python-dev python-pip python-virtualenv doxygen ditaa; do
+	if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+            # add a space after old values
+	    missing="${missing:+$missing }$package"
+	fi
+    done
+    if [ -n "$missing" ]; then
+	echo "$0: missing required packages, please install them:" 1>&2
+	echo "sudo apt-get install $missing"
+	exit 1
+    fi
+else
+    for command in virtualenv doxygen ditaa; do
+	if ! command -v "$command" >/dev/null; then
+            # add a space after old values
+	    missing="${missing:+$missing }$package"
+	fi
+    done
+    if [ -n "$missing" ]; then
+	echo "$0: missing required command, please install them:" 1>&2
+	echo "$missing"
+	exit 1
+    fi
+fi
+
 if [ ! -e build-doc/doxygen/xml ]; then
     doxygen
 fi
-
-dia --filter=png-libart --export=doc/overview.png.tmp doc/overview.dia
-
-mv -- doc/overview.png.tmp doc/overview.png
 
 cat src/osd/PG.h src/osd/PG.cc | doc/scripts/gen_state_diagram.py > doc/dev/peering_graph.generated.dot
 
@@ -34,6 +56,8 @@ if [ -z "$(git rev-parse --default HEAD)" ]; then
     git pull --ff-only https://github.com/michaeljones/breathe.git master
 fi
 cd ..
+
+./virtualenv/bin/pip install --quiet -e 'git+https://github.com/NewDreamNetwork/sphinx-ditaa.git#egg=sphinx-ditaa'
 
 install -d -m0755 \
     output/html \
