添加vs工程

diff --git a/admin/build-doc b/admin/build-doc
--- a/admin/build-doc
+++ b/admin/build-doc
@@ -20,8 +20,8 @@ if command -v dpkg >/dev/null; then
         exit 1
     fi
 elif command -v yum >/dev/null; then
-    for package in python-devel python-pip python-virtualenv doxygen ditaa ant libxml2-devel libxslt-devel Cython graphviz; do
-	if ! rpm -q $package >/dev/null ; then
+    for package in ant ditaa doxygen libxslt-devel libxml2-devel graphviz python3-devel python3-pip python3-virtualenv python3-Cython; do
+	if ! rpm -q --whatprovides $package >/dev/null ; then
 		missing="${missing:+$missing }$package"
 	fi
     done
@@ -31,17 +31,15 @@ elif command -v yum >/dev/null; then
         exit 1
     fi
 else
-    for command in virtualenv doxygen ant ditaa cython; do
-	command -v "$command" > /dev/null;
-	ret_code=$?
-	if [ $ret_code -ne 0 ]; then
+    for command in dot virtualenv doxygen ant ditaa cython; do
+        if ! command -v "$command" > /dev/null; then
             # add a space after old values
-	    missing="${missing:+$missing }$command"
-	fi
+            missing="${missing:+$missing }$command"
+        fi
     done
     if [ -n "$missing" ]; then
-	echo "$0: missing required command, please install them:" 1>&2
-	echo "$missing"
+        echo "$0: missing required command, please install them:" 1>&2
+        echo "$missing" 1>&2
 	exit 1
     fi
 fi
@@ -50,69 +48,57 @@ fi
 # for availability of commands
 set -e
 
-cat $TOPDIR/src/osd/PG.h $TOPDIR/src/osd/PG.cc | $TOPDIR/doc/scripts/gen_state_diagram.py > $TOPDIR/doc/dev/peering_graph.generated.dot
-
-cd build-doc
-
 [ -z "$vdir" ] && vdir="$TOPDIR/build-doc/virtualenv"
 
 if [ ! -e $vdir ]; then
-    virtualenv --system-site-packages $vdir -p python2
+    virtualenv --python=python3 $vdir
 fi
-$vdir/bin/pip install --quiet -r $TOPDIR/admin/doc-requirements.txt
+
+$vdir/bin/pip install --quiet \
+              -r $TOPDIR/admin/doc-requirements.txt \
+              -r $TOPDIR/admin/doc-python-common-requirements.txt
+BUILD_DOC=1 $vdir/bin/pip install --quiet \
+         -r $TOPDIR/admin/doc-pybind.txt
 
 install -d -m0755 \
     $TOPDIR/build-doc/output/html \
     $TOPDIR/build-doc/output/man
 
-# To avoid having to build librbd to build the Python bindings to build the docs,
-# create a dummy librbd.so that allows the module to be imported by sphinx.
-# the module are imported by the "automodule::" directive.
-mkdir -p $vdir/lib
-export LD_LIBRARY_PATH="$vdir/lib"
-export PYTHONPATH=$TOPDIR/src/pybind
-
-# FIXME(sileht): I dunno how to pass the include-dirs correctly with pip
-# for build_ext step, it should be:
-# --global-option=build_ext --global-option="--cython-include-dirs $TOPDIR/src/pybind/rados/"
-# but that doesn't work, so copying the file in the rbd module directly, that's ok for docs
-for bind in rados rbd cephfs rgw; do
-    if [ ${bind} != rados ]; then
-        cp -f $TOPDIR/src/pybind/rados/rados.pxd $TOPDIR/src/pybind/${bind}/
-    fi
-    ln -sf lib${bind}.so.1 $vdir/lib/lib${bind}.so
-    gcc -shared -o $vdir/lib/lib${bind}.so.1 -xc /dev/null
-    BUILD_DOC=1 \
-        CFLAGS="-iquote$TOPDIR/src/include" \
-        CPPFLAGS="-iquote$TOPDIR/src/include" \
-        LDFLAGS="-L$vdir/lib -Wl,--no-as-needed" \
-        $vdir/bin/pip install $TOPDIR/src/pybind/${bind}
-    # rgwfile_version(), librgw_create(), rgw_mount()
-    nm $vdir/lib/python*/*-packages/${bind}.so | grep -E "U (lib)?${bind}" | \
-        awk '{ print "void "$2"(void) {}" }' | \
-        gcc -shared -o $vdir/lib/lib${bind}.so.1 -xc -
-    if [ ${bind} != rados ]; then
-        rm -f $TOPDIR/src/pybind/${bind}/rados.pxd
-    fi
+for opt in "$@"; do
+    case $opt in
+        html|man|livehtml)
+            sphinx_targets="$sphinx_targets $opt"
+            shift
+            ;;
+        --)
+            shift
+            break
+    esac
 done
 
-if [ -z "$@" ]; then
+if [ -z "$sphinx_targets" ]; then
     sphinx_targets="html man"
-else
-    sphinx_targets=$@
 fi
+
+cd build-doc
+
 for target in $sphinx_targets; do
-    builder=$target
+    # Build with -W so that warnings are treated as errors and this fails
     case $target in
         html)
-            builder=dirhtml
+            $vdir/bin/sphinx-build -W --keep-going -a -b dirhtml -d doctrees \
+                                   $TOPDIR/doc $TOPDIR/build-doc/output/$target
             ;;
         man)
-            extra_opt="-t man"
+            $vdir/bin/sphinx-build -W --keep-going -a -b man -t man -d doctrees \
+                                   $TOPDIR/doc $TOPDIR/build-doc/output/$target
+            ;;
+        livehtml)
+            $vdir/bin/pip install --quiet sphinx-autobuild
+            $vdir/bin/sphinx-autobuild --re-ignore '.*\.dot' "$@" \
+                                       $TOPDIR/doc $TOPDIR/build-doc/output/html
             ;;
     esac
-    $vdir/bin/sphinx-build -a -b $builder $extra_opt -d doctrees \
-                           $TOPDIR/doc $TOPDIR/build-doc/output/$target
 done
 
 #
@@ -125,9 +111,11 @@ rm -rf $JAVADIR/doc
 ant -buildfile $JAVADIR/build.xml docs
 
 # Create clean target directory
-JAVA_OUTDIR=$TOPDIR/build-doc/output/html/api/libcephfs-java/javadoc
+JAVA_OUTDIR=$TOPDIR/build-doc/output/html/cephfs/api/libcephfs-java/javadoc
 rm -rf $JAVA_OUTDIR
 mkdir $JAVA_OUTDIR
 
 # Copy JavaDocs to target directory
 cp -a $JAVADIR/doc/* $JAVA_OUTDIR/
+
+echo "SUCCESS"
diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/bash -e
 
 if [ ! -d .git ]; then
     echo "no .git present.  run this from the base dir of the git checkout."
@@ -6,9 +6,16 @@ if [ ! -d .git ]; then
 fi
 
 version=$1
-[ -z "$version" ] && version=`git describe --match 'v*' | sed 's/^v//'`
-outfile="ceph-$version"
+[ -z "$version" ] && version=$(git describe --long --match 'v*' | sed 's/^v//')
+if expr index $version '-' > /dev/null; then
+    rpm_version=$(echo $version | cut -d - -f 1-1)
+    rpm_release=$(echo $version | cut -d - -f 2- | sed 's/-/./')
+else
+    rpm_version=$version
+    rpm_release=0
+fi
 
+outfile="ceph-$version"
 echo "version $version"
 
 # update submodules
@@ -19,6 +26,100 @@ if ! git submodule sync || ! git submodule update $force --init --recursive; the
     echo "  Network connectivity might be required."
     exit 1
 fi
+
+download_from() {
+    fname=$1
+    shift
+    sha256=$1
+    shift
+    set +e
+    while true; do
+        url_base=$1
+        shift
+        if [ -z $url_base ]; then
+            echo "Error: failed to download $name."
+            exit
+        fi
+        url=$url_base/$fname
+        wget -c --no-verbose -O $fname $url
+        if [ $? != 0 -o ! -e $fname ]; then
+            echo "Download of $url failed"
+        elif [ $(sha256sum $fname | awk '{print $1}') != $sha256 ]; then
+            echo "Error: failed to download $name: SHA256 mismatch."
+        else
+            break
+        fi
+    done
+    set -e
+}
+
+download_boost() {
+    boost_version=$1
+    shift
+    boost_sha256=$1
+    shift
+    boost_version_underscore=$(echo $boost_version | sed 's/\./_/g')
+    boost_fname=boost_${boost_version_underscore}.tar.bz2
+    download_from $boost_fname $boost_sha256 $*
+    tar xjf $boost_fname -C src \
+        --exclude="$boost_version_underscore/libs/*/doc" \
+        --exclude="$boost_version_underscore/libs/*/example" \
+        --exclude="$boost_version_underscore/libs/*/examples" \
+        --exclude="$boost_version_underscore/libs/*/meta" \
+        --exclude="$boost_version_underscore/libs/*/test" \
+        --exclude="$boost_version_underscore/tools/boostbook" \
+        --exclude="$boost_version_underscore/tools/quickbook" \
+        --exclude="$boost_version_underscore/tools/auto_index" \
+        --exclude='doc' --exclude='more' --exclude='status'
+    mv src/boost_${boost_version_underscore} src/boost
+    tar cf ${outfile}.boost.tar ${outfile}/src/boost
+    rm -rf src/boost
+}
+
+download_liburing() {
+    liburing_version=$1
+    shift
+    liburing_sha256=$1
+    shift
+    liburing_fname=liburing-${liburing_version}.tar.gz
+    download_from $liburing_fname $liburing_sha256 $*
+    tar xzf $liburing_fname -C src  \
+        --exclude=debian \
+        --exclude=examples \
+        --exclude=man \
+        --exclude=test
+    # normalize the names, liburing-0.7 if downloaded from git.kernel.dk,
+    # liburing-liburing-0.7 from github.com
+    mv src/liburing-* src/liburing
+    tar cf ${outfile}.liburing.tar ${outfile}/src/liburing
+    rm -rf src/liburing
+}
+
+build_dashboard_frontend() {
+  CURR_DIR=`pwd`
+  TEMP_DIR=`mktemp -d`
+
+  $CURR_DIR/src/tools/setup-virtualenv.sh $TEMP_DIR
+  $TEMP_DIR/bin/pip install nodeenv
+  $TEMP_DIR/bin/nodeenv -p --node=12.18.2
+  cd src/pybind/mgr/dashboard/frontend
+
+  . $TEMP_DIR/bin/activate
+  NG_CLI_ANALYTICS=false timeout 1h npm ci
+  echo "Building ceph-dashboard frontend with build:localize script";
+  # we need to use "--" because so that "--prod" survives accross all
+  # scripts redirections inside package.json
+  npm run build:localize -- --prod
+  deactivate
+  cd $CURR_DIR
+  rm -rf $TEMP_DIR
+  tar cf dashboard_frontend.tar $outfile/src/pybind/mgr/dashboard/frontend/dist
+}
+
+generate_rook_ceph_client() {
+  $outfile/src/pybind/mgr/rook/generate_rook_ceph_client.sh
+  tar cf rook_ceph_client.tar $outfile/src/pybind/mgr/rook/rook_client/*.py
+}
 
 # clean out old cruft...
 echo "cleanup..."
@@ -34,35 +135,39 @@ bin/git-archive-all.sh --prefix ceph-$version/ \
 # populate files with version strings
 echo "including src/.git_version, ceph.spec"
 
-(git rev-parse HEAD ; git describe) 2> /dev/null > src/.git_version
+(git rev-parse HEAD ; echo $version) 2> /dev/null > src/.git_version
 
-# if the version has '-' in it, it has a 'release' part,
-# like vX.Y.Z-N-g<shortsha1>.  If it doesn't, it's just
-# vX.Y.Z.  Handle both, and translate - to . for rpm
-# naming rules (the - separates version and release).
-
-if expr index $version '-' > /dev/null; then
-	rpm_version=`echo $version | cut -d - -f 1-1`
-	rpm_release=`echo $version | cut -d - -f 2- | sed 's/-/./'`
-else
-	rpm_version=$version
-	rpm_release=0
-fi
-
-
-for spec in ceph.spec.in alpine/APKBUILD.in; do
+for spec in ceph.spec.in; do
     cat $spec |
-        sed "s/@VERSION@/$rpm_version/g" |
+        sed "s/@PROJECT_VERSION@/$rpm_version/g" |
         sed "s/@RPM_RELEASE@/$rpm_release/g" |
         sed "s/@TARBALL_BASENAME@/ceph-$version/g" > `echo $spec | sed 's/.in$//'`
 done
 ln -s . $outfile
-tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec $outfile/alpine/APKBUILD
-tar --concatenate -f $outfile.both.tar $outfile.version.tar
-tar --concatenate -f $outfile.both.tar $outfile.tar
-mv $outfile.both.tar $outfile.tar
+tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec
+# NOTE: If you change this version number make sure the package is available
+# at the three URLs referenced below (may involve uploading to download.ceph.com)
+boost_version=1.73.0
+download_boost $boost_version 4eb3b8d442b426dc35346235c8733b5ae35ba431690e38c6a8263dce9fcbb402 \
+               https://dl.bintray.com/boostorg/release/$boost_version/source \
+               https://downloads.sourceforge.net/project/boost/boost/$boost_version \
+               https://download.ceph.com/qa
+download_liburing 0.7 8e2842cfe947f3a443af301bdd6d034455536c38a455c7a700d0c1ad165a7543 \
+                  https://github.com/axboe/liburing/archive \
+                  https://git.kernel.dk/cgit/liburing/snapshot
+build_dashboard_frontend
+generate_rook_ceph_client
+for tarball in $outfile.version   \
+               $outfile.boost     \
+               $outfile.liburing  \
+               dashboard_frontend \
+               rook_ceph_client   \
+               $outfile; do
+    tar --concatenate -f $outfile.all.tar $tarball.tar
+    rm $tarball.tar
+done
+mv $outfile.all.tar $outfile.tar
 rm $outfile
-rm -f $outfile.version.tar
 
 echo "compressing..."
 bzip2 -9 $outfile.tar
